"""Derive the per-volume time coverage from the diaries themselves and check it.

    python tools/build_volume_coverage.py <corpus_dir> [--write configs/volume_coverage.yaml]

Reads the title page of every volume from ``<corpus_dir>/corpus.json`` (the
"Ornithologische Tagebuchnotizen … <Monat Jahr> - <Monat Jahr>" line on one of
the first pages) and compares it with the empirical entry-date distribution in
``<corpus_dir>/entries.csv`` (2nd/98th percentile). Prints a table; with
``--write`` it (re)writes the YAML table used by ``normalization/coverage.py``,
keeping the manual overrides for volumes whose title page is missing or belongs
to another volume (Vol 15's title scan is Vol 1's).
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import re
from pathlib import Path

MONTHS = {"jan": 1, "januar": 1, "feb": 2, "februar": 2, "märz": 3, "maerz": 3, "mar": 3, "apr": 4, "april": 4,
          "mai": 5, "jun": 6, "juni": 6, "jul": 7, "juli": 7, "aug": 8, "august": 8, "sep": 9, "sept": 9,
          "september": 9, "okt": 10, "oktober": 10, "oct": 10, "nov": 11, "november": 11, "dez": 12,
          "dezember": 12, "dec": 12, "december": 12}
_MON = r"(?:jan(?:uar)?|feb(?:ruar)?|m[äa]e?rz|mar|apr(?:il)?|mai|juni?|juli?|aug(?:ust)?|sept?(?:ember)?|okt(?:ober)?|oct|nov(?:ember)?|dez(?:ember)?|dec(?:ember)?)"
TITLE = re.compile(rf"({_MON})\.?\s*(1[89]\d\d)\s*[-–—]\s*(?:({_MON})\.?\s*(1[89]\d\d))?", re.IGNORECASE)
# manual overrides: volume -> (start, end, source)
OVERRIDES = {
    15: ("1937-05", "1938-10", "inferred from Vol 14/16 title pages and the entry-date distribution (title page scan is Vol 1's)"),
    34: (None, "1965-12", "title page: Mai 1964 - (open); diaries end 1965"),
}


def ym(month: str, year: str) -> str:
    return f"{int(year):04d}-{MONTHS[month.lower().rstrip('.')]:02d}"


def title_spans(corpus_json: Path) -> dict[int, tuple[str | None, str | None, str]]:
    pages = json.loads(corpus_json.read_text(encoding="utf-8"))
    by_vol: dict[int, list] = collections.defaultdict(list)
    for p in pages:
        by_vol[int(p["volume"])].append(p)
    out = {}
    for v, ps in by_vol.items():
        for p in sorted(ps, key=lambda p: int(p["scan"]))[:8]:
            txt = " ".join(r.get("text", "").replace("\n", " ") for r in p["regions"])
            if "Tagebuchnotizen" not in txt:
                continue
            m = TITLE.search(txt)
            if not m:
                continue
            start = ym(m.group(1), m.group(2))
            end = ym(m.group(3), m.group(4)) if m.group(3) else None
            out[v] = (start, end, "title page: " + m.group(0).strip())
            break
    return out


def empirical(entries_csv: Path) -> dict[int, tuple[str, str, int]]:
    rows = csv.DictReader(entries_csv.open(encoding="utf-8"))
    dates: dict[int, list[str]] = collections.defaultdict(list)
    for r in rows:
        d = (r.get("date_norm") or "").strip()
        if len(d) >= 7 and d[:4].isdigit():
            dates[int(r["volume"])].append(d[:7])
    out = {}
    for v, ds in dates.items():
        ds.sort()
        out[v] = (ds[int(len(ds) * 0.02)], ds[min(len(ds) - 1, int(len(ds) * 0.98))], len(ds))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("corpus_dir")
    ap.add_argument("--write", default=None, help="write the YAML table to this path")
    args = ap.parse_args()
    corpus = Path(args.corpus_dir)
    titles = title_spans(corpus / "corpus.json")
    emp = empirical(corpus / "entries.csv")
    table = {}
    print(f"{'vol':>3}  {'title start':11} {'title end':10}  {'P2':7} {'P98':7} {'n':>5}  note")
    for v in sorted(set(titles) | set(emp)):
        start, end, src = titles.get(v, (None, None, "no title page found"))
        if v in OVERRIDES:
            o_start, o_end, o_src = OVERRIDES[v]
            start, end, src = o_start or start, o_end or end, o_src
        p2, p98, n = emp.get(v, ("-", "-", 0))
        note = ""
        if start and p2 < start[:7] and (int(start[:4]) * 12 + int(start[5:7])) - (int(p2[:4]) * 12 + int(p2[5:7])) > 2:
            note = "P2 well before title start (misfiled/retrospective content?)"
        print(f"{v:>3}  {start or '-':11} {end or '-':10}  {p2:7} {p98:7} {n:>5}  {note}")
        table[v] = {"start": start, "end": end, "source": src}
    if args.write:
        lines = ["# generated by tools/build_volume_coverage.py — see the header of the checked-in file for the rationale",
                 "volumes:"]
        for v in sorted(table):
            t = table[v]
            lines.append(f"  {v}: {{start: {t['start']}, end: {t['end']}, source: {json.dumps(t['source'], ensure_ascii=False)}}}")
        Path(args.write).write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("wrote", args.write)


if __name__ == "__main__":
    main()
